### ISSUE TITLE
What's the current status with k4dirstat and kdirstat?

### ISSUE THREAD

**Issue by thibaultmol** [thomas-joiner/k4dirstat#3]
Title^

**Comment by thomas-joiner** [comment]
First, sorry for the delay in replying. My job has been fairly hectic, and I have not had much time to reply, and when I did have time, I kept forgetting about it.

If by "kdirstat" you are referring to the original project, there has been no announcement that I am aware of, but I'm fairly sure that it has been long abandoned.

As for this project there is no active development. When I last used it on KDE 4.x, it worked, however, I have since switched to using XFCE, so no testing has been done on KDE 5.x.

I am personally not averse to continuing development on this project, however, since it appears that [Jerome Robert's k4dirstat](https://bitbucket.org/jeromerobert/k4dirstat/wiki/Home) is still being maintained, I will mark this project as being abandoned. The reason for the confusing names is that both of us posted our versions around the same time. I believe that it is his version that has been packaged by most distributions.
